### ISSUE TITLE
low-pass filter or high-frequency roll-off options

### ISSUE THREAD

**Issue by wolftune** [brarcher/baby-sleep-sounds#18]
So, this would be the one thing that would take this app to the next level. Babies (and adults) sleep better when the sounds aren't really high-pitched but are muffled. Think rain outside while you are inside or the fluid-filled sound of the womb… (this is widely known, check Happiest Baby books for example).

So, the best approach would be to include a simple low-pass filter or some sort of high-frequency roll-off option as a very simple one- or two-setting EQ effect. That would make this app really effective.

Thanks

**Comment by brarcher** [comment]
I like the idea. I'll look into it. Thanks for the suggestion.

**Comment by wolftune** [comment]
Great! In the mean-time, I' using a portable speaker and sticking it under some clothing!

**Comment by brarcher** [comment]
Having looked into this, I have a question for you. Is it important to select the roll off frequency for the lowpass filter, or is having an option to apply a lowpass filter at a preselected frequency sufficient?

I have something working locally, however if the lowpass filter roll off frequency is selectable there is a noticeable delay before playback starts as the filter is applied to the file before playback. Further, performing a crossfade may be a bit tricky to do online and still keep things simple.

If configuring the filter is not that important, or at least if there are several preset filter options to select from, I can perform the lowpass filter and crossfade offline, making the playback very simple.

What are your thoughts?

**Comment by brarcher** [comment]
On second thought, I think I have reduced the performance hit for performing the crossfade and lowpass filtering online. I'll add some changes which will add a configurable option for a lowpass filter:

![screenshot_2016-08-27-22-34-23](https://cloud.githubusercontent.com/assets/5264535/18031324/809d12ea-6ca9-11e6-80aa-94188781233e.png)

**Comment by brarcher** [comment]
This should now be resolved. Look for this change in the next release. If you have any feedback, please let me know. (:

**Comment by wolftune** [comment]
Amazing and fast work!!! Thanks so much!

To be clear, I think this is the sort of thing where the *optimal* case provides people a wide range of control to tweak as desired but a good default that avoids encouraging people to tweak when they don't care to waste time exploring that.

In this case, I think *any* initial implementation is a great step, and iterating is better than aiming for perfection right away. This seems like an excellent improvement overall, and I look forward to testing it!
