### ISSUE TITLE
Crackling of fire?

### ISSUE THREAD

**Issue by mcepl** [brarcher/baby-sleep-sounds#60]
Something of this sort https://www.youtube.com/watch?v=3ohDcpxVK74 (I wonder whether https://www.youtube.com/channel/UCMzbrcOG-edOxonhLbsOD4Q would allow public domain use of some of his fireplaces)?

It seems to me that natural sounds (rain, shower, stream, river) work way better than the artificial ones, which resemble each other too much).

**Comment by brarcher** [comment]
I'm up for adding a fireplace sound. There will need to be a better source than the youtube video; if I recall correctly the standard youtube license prevents playing youtube content outside of youtube (e.g. downloading it for playback later).

If you find a source which is compatible with this application (creative commons, personal-only use, etc) let me know and I can incorporate it.

**Comment by mcepl** [comment]
yes, certainly, I thought you would contact the owner of the channel and ask him.

**Comment by brarcher** [comment]
I'll probably not reach out myself, as there are probably other, easier, sound sources to pick from. For example, the following found with a quick search should have a license that allows the sounds to be packaged into the app. How do any of the following sound:
- freesoundeffects.com
  * [Crackling Fireplace](https://www.freesoundeffects.com/mp3_89305.mp3)
  * [fireplace](https://www.freesoundeffects.com/mp3_89310.mp3)
  * [Crackling Fire](https://www.freesoundeffects.com/mp3_426781.mp3)
- soundjay.com
  * [Campfire](https://www.soundjay.com/nature/campfire-1.mp3)
  * [Fire Sound Effect 01](https://www.soundjay.com/nature/fire-1.mp3)
  * [Fire Sound Effect 02](https://www.soundjay.com/nature/fire-2.mp3)
- freesound.org
  * [fire_embers_large_campfire.aif](https://freesound.org/people/Dynamicell/sounds/17554/)
  * [Campfire_2.wav](https://freesound.org/people/zmb94/sounds/74964/)
- environment-other.ambient-mixer.com
  * [Some fireplace](https://environment-other.ambient-mixer.com/fireplace)

**Comment by mcepl** [comment]
All three from freesoundeffects.com give me 404. soundjay.com's ``Campfire`` sounds lovely. Both ``Fire Sound Effect``s from that site are to my feeling too flamey and too little crackly (if these are English words ;)) ``Fire embers large campfire`` is good, but still ``Campfire`` is better. ``Campfire_2`` is OTOH just opposite to ``Fire Sound Effect``s … it is so crackly that it is more distracting than soothing, IMHO. ``Some fireplace`` is nice, I would say close second best. Still I would vote for ``Campfire`` from soundjay.com.

**Comment by brarcher** [comment]
I looked at the [terms of service](https://www.soundjay.com/tos.html) for soundjay more carefully, and found the following:

> But you are NOT allowed to
> - distribute the sounds in apps or computer programs that are clearly sound related in nature (such as sound machine, funny sounds app, sound therapy app, ringtone maker, etc.). If you are developing such programs, contact us for licensing options.

I've contacted soundjay to see if they will allow me to use their campfire sound in the application without a licensing fee. I'm awaiting a response.

**Comment by brarcher** [comment]
I've received the following permission from SoundJay to use the sound file:

> Yes, you have our permission to use the campfire-1.mp3 for the purpose intended as mentioned in your email.

Which was:  I am interested in adding a derivation of [this sound](https://www.soundjay.com/nature/campfire-1.mp3) to the Baby Sleep Sounds apps. A shorter version of the mp3 would be used, perhaps up to 10 seconds, which would be looped by the application.

> This permission is for the https://www.soundjay.com/nature/campfire-1.mp3 only.
If you can, please mention something like “Campfire-1.mp3 Copyright SoundJay.com Used with Permission"

I'll work on adding the sound to the app.

**Comment by brarcher** [comment]
The new campfire sound has been added. Look for it in the next release. Thanks for the suggestion and the help in vetting different options.

**Comment by mcepl** [comment]
Perfect, thank you!
