### ISSUE TITLE
Stop playing after N minutes 

### ISSUE THREAD

**Issue by vide** [brarcher/baby-sleep-sounds#9]
Could you please add an option to stop playing the sound after a specific number of minutes have passed?

Thanks!

**Comment by vide** [comment]
Btw thanks for thos app and for sharing it

**Comment by brarcher** [comment]
Glad the app is useful. (:

If I may ask, are you using the app to actually help a baby get to sleep or stay asleep? Originally I created the app with this intention, but found it not too useful for my child. Maybe a baby needs to be a certain age before it is useful or effective, not sure. Perhaps I need to be more patient and give it another try.

Thanks for the feature idea. Good idea, I'll see about adding a timeout option at some point.

**Comment by vide** [comment]
Hello! Well, actually yes, white noises (fan, dryer etc) helped and are still helping my baby daughter to sleep, it's almost like magic! But sometimes you go to sleep at the same moment with the noise activated and you don't want the noise all night long.

**Comment by vide** [comment]
Hello! Well, actually yes, white noises (fan, dryer etc) helped and are still helping my baby daughter to sleep, it's almost like magic! But sometimes you go to sleep at the same moment with the noise activated and you don't want the noise all night long.

**Comment by brarcher** [comment]
I've added this feature, and it will appear in v0.2 which should make its way to F-Droid in a few days. To keep it simple there is a drop down of options instead of a free-form field for entering the exact time. I hope that it will be sufficient.

**Comment by vide** [comment]
Thank you very much, that was quick! As soon as it gets updated on f-droid I will test it.

**Comment by vide** [comment]
Just installed 0.2, thank you very much!
